// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4mVR8CEReuNQuQi7fGf25XqngeCoiDsY',
    appId: '1:644111868719:web:d4eb4f8c01c92b7413b7da',
    messagingSenderId: '644111868719',
    projectId: 'royal-hotel-a6b0a',
    authDomain: 'royal-hotel-a6b0a.firebaseapp.com',
    storageBucket: 'royal-hotel-a6b0a.appspot.com',
    measurementId: 'G-CNPK1WL4PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQgpFXJ53HP5Hyxaf92PFMda2EaPc0ds',
    appId: '1:644111868719:android:e719d9b9b85332f613b7da',
    messagingSenderId: '644111868719',
    projectId: 'royal-hotel-a6b0a',
    storageBucket: 'royal-hotel-a6b0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rhffkIjxDVa2se9k1VUaoMB32XvUIJ0',
    appId: '1:644111868719:ios:765b362727078b1213b7da',
    messagingSenderId: '644111868719',
    projectId: 'royal-hotel-a6b0a',
    storageBucket: 'royal-hotel-a6b0a.appspot.com',
    iosBundleId: 'com.example.royalHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rhffkIjxDVa2se9k1VUaoMB32XvUIJ0',
    appId: '1:644111868719:ios:11ffb67cf92f07ac13b7da',
    messagingSenderId: '644111868719',
    projectId: 'royal-hotel-a6b0a',
    storageBucket: 'royal-hotel-a6b0a.appspot.com',
    iosBundleId: 'com.example.royalHotel.RunnerTests',
  );
}
